apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-bot
  name: argocd-bot
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: argocd-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-bot
  name: argocd-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-bot
    spec:
      containers:
      - command:
        - npm
        - start
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: PRIVATE_KEY_PATH
          value: /data/key.pem
        - name: ARGO_CD_SERVER_IP
          valueFrom:
            secretKeyRef:
              key: ARGOCD_SERVER
              name: argocd-bot-secret
        - name: ARGOCD_SERVER
          valueFrom:
            secretKeyRef:
              key: ARGOCD_SERVER
              name: argocd-bot-secret
        - name: ARGO_CD_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: TOKEN
              name: argocd-bot-secret
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: TOKEN
              name: argocd-bot-secret
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              key: APP_ID
              name: argocd-bot-secret
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: argocd-bot-secret
        - name: GITHUB_REPO
          valueFrom:
            secretKeyRef:
              key: GITHUB_REPO
              name: argocd-bot-secret
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: WEBHOOK_SECRET
              name: argocd-bot-secret
        image: argocd-bot:latest
        imagePullPolicy: Always
        name: argocd-bot
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 1
          tcpSocket:
            port: 3000
        volumeMounts:
        - mountPath: /data
          name: app-private-key
          readOnly: true
      volumes:
      - name: app-private-key
        secret:
          secretName: argocd-bot-secret
