apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-bot
  name: argocd-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-bot
    spec:
      containers:
      - name: argocd-bot
        command: [npm, start]
        image: argocd-bot:latest
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: PRIVATE_KEY_PATH
          value: "/data/key.pem"
        - name: ARGO_CD_SERVER_IP
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: ARGOCD_SERVER
        - name: ARGOCD_SERVER
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: ARGOCD_SERVER
        - name: ARGO_CD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: TOKEN
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: TOKEN
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: APP_ID
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: GITHUB_TOKEN
        - name: GITHUB_REPO
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: GITHUB_REPO
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: argocd-bot-secret
              key: WEBHOOK_SECRET
        volumeMounts:
        - name: app-private-key
          mountPath: "/data"
          readOnly: true
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 1
      volumes:
      - name: app-private-key
        secret:
          secretName: argocd-bot-secret
